adb shell pm uninstall com.ark.files
adb shell pm uninstall com.google.android.apps.nbu.files
adb shell pm uninstall com.widestudio.files
adb shell pm uninstall antivirus.cleaner.speedup.junk
adb shell pm uninstall com.agedstudio.card.solitaire.klondike
adb shell pm uninstall com.amazing.booster
adb shell pm uninstall com.amazing.files
adb shell pm uninstall com.amazing.security
adb shell pm uninstall com.antidetector.spyappfinder
adb shell pm uninstall com.autocleaner.android.booster.clean
adb shell pm uninstall com.awesome.boost.junkcleaner
adb shell pm uninstall com.balaganovrocks.dodocleaner
adb shell pm uninstall com.bettercleaner.cleaner
adb shell pm uninstall com.bright.cleaner.junkfiles
adb shell pm uninstall com.circleback.cleanup
adb shell pm uninstall com.clean.keep
adb shell pm uninstall com.cleandroidide.protects.force
adb shell pm uninstall com.cleanme.android.coolapp
adb shell pm uninstall com.piriform.ccleaner
adb shell pm uninstall com.cleanobjects.protectspeed.boost.android
adb shell pm uninstall com.coobox.boosterpal
adb shell pm uninstall com.coobox.magic.cleaner
adb shell pm uninstall com.coobox.magic.files
adb shell pm uninstall com.coobox.securitypal
adb shell pm uninstall com.daily.clean.booster.super
adb shell pm uninstall com.dr.clean
adb shell pm uninstall com.fabulous.booster
adb shell pm uninstall com.fabulous.cleaner
adb shell pm uninstall com.fabulous.files
adb shell pm uninstall com.fabulous.security
adb shell pm uninstall com.lemongame.freecell.solitaire
adb shell pm uninstall com.manager.booster.smart
adb shell pm uninstall com.mars.phone.cleaner
adb shell pm uninstall com.mastertool.super.cleanapp
adb shell pm uninstall com.mobilityware.solitaire
adb shell pm uninstall com.myhomescreen.access
adb shell pm uninstall com.myhomescreen.email
adb shell pm uninstall com.myhomescreen.sms
adb shell pm uninstall com.noxgroup.app.security
adb shell pm uninstall com.omni.cleaner.sagitta
adb shell pm uninstall com.optimize.clean.onekeyboost
adb shell pm uninstall com.pluto.booster.speed.boost.junk.cleaner
adb shell pm uninstall com.pluto.cleaner.speed
adb shell pm uninstall com.phone.boost.clean.optimizer
adb shell pm uninstall com.phone.cleaner.junk.file.clean.cache.master
adb shell pm uninstall com.piriform.ccleaner
adb shell pm uninstall com.pluto.files.speed.boost.junk.cleaner
adb shell pm uninstall com.pluto.security.antivirus.speedboost.viruscleaner
adb shell pm uninstall com.powerful.clean.booster
adb shell pm uninstall com.quick.boost.android.cleaner
adb shell pm uninstall com.rajat.superbooster.cleaner
adb shell pm uninstall com.relaxingbraintraining.solitairekingdom
adb shell pm uninstall com.smart.master.super
adb shell pm uninstall com.solitaire.card
adb shell pm uninstall com.spaces.booster.cleaner
adb shell pm uninstall com.speedclean.master.expert
adb shell pm uninstall com.sup.phone.cleaner.booster.app
adb shell pm uninstall com.supreme.cleaner
adb shell pm uninstall com.symantec.cleansweep
adb shell pm uninstall com.vplus.cleaner
adb shell pm uninstall com.widestudio.clean
adb shell pm uninstall com.wuxdstudio.uppercleaner
adb shell pm uninstall fast.phone.clean
adb shell pm uninstall com.widestudio.clean
adb shell pm uninstall info.myapp.allemailaccess
adb shell pm uninstall phone.cleaner.antivirus.speed.booster
adb shell pm uninstall solitaire.arcadegames.freecard.solitaireplus.epic.klodike
adb shell pm uninstall solitaire.classic.journey.klondike.puzzle.card
adb shell pm uninstall solitaire.mahjongmaker.collection.card.solitaire.klondike
adb shell pm uninstall solitaire.solitairemaker.solitaire.klondike.card
adb shell pm uninstall spider.solitaire.card.bgames